version: '3'
services:
  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    enviroment:
    ACCEPT_EULA: "Y"
    SA_PASSWORD: "pa55w0rd!"
    MSSQL_PID: "Express"
  ports:
    - "1443:1443"