// <auto-generated />
using GraphQLTestApi.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GraphQLTestApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220623152159_Adding_Department_entity")]
    partial class Adding_Department_entity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GraphQLTestApi.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            Name = "TI"
                        },
                        new
                        {
                            DepartmentId = 2,
                            Name = "Accounting"
                        },
                        new
                        {
                            DepartmentId = 3,
                            Name = "RRHH"
                        });
                });

            modelBuilder.Entity("GraphQLTestApi.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Designation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 0,
                            DepartmentId = 0,
                            Name = "Barry Allen"
                        },
                        new
                        {
                            Id = 2,
                            Age = 0,
                            DepartmentId = 2,
                            Name = "Hal Jordan"
                        },
                        new
                        {
                            Id = 3,
                            Age = 0,
                            DepartmentId = 3,
                            Name = "Wally West"
                        },
                        new
                        {
                            Id = 4,
                            Age = 0,
                            DepartmentId = 3,
                            Name = "Donna Trhoy"
                        },
                        new
                        {
                            Id = 5,
                            Age = 0,
                            DepartmentId = 1,
                            Name = "Bart Allen"
                        },
                        new
                        {
                            Id = 6,
                            Age = 0,
                            DepartmentId = 1,
                            Name = "Oliver Queen"
                        });
                });

            modelBuilder.Entity("GraphQLTestApi.Models.Employee", b =>
                {
                    b.HasOne("GraphQLTestApi.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("GraphQLTestApi.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
