// <auto-generated />
using GraphQLTestApi.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GraphQLTestApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220622232408_InitialDb")]
    partial class InitialDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GraphQLTestApi.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Designation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Barry Allen"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Hal Jordan"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Wally West"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Donna Trhoy"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Bart Allen"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Oliver Queen"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
